import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = (quote: any) => {
    const doc = new jsPDF();

    // -- Header --
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185); // Professional Blue
    doc.text("COMMERCIAL QUOTATION", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by BOQ Automator", 14, 26);

    // -- Client Info & Date --
    const today = new Date().toLocaleDateString();

    doc.setFontSize(11);
    doc.setTextColor(0);
    doc.text(`Client: ${quote.clientName || "Valued Customer"}`, 14, 40);
    doc.text(`Date: ${today}`, 160, 40);
    doc.text(`Quote Ref: #${quote.id.slice(-6).toUpperCase()}`, 160, 46);

    // -- Table --
    const tableColumn = ["Part Code", "Description", "Qty", "Unit Price", "Total"];
    const tableRows: any[] = [];

    quote.items.forEach((item: any) => {
        const itemData = [
            item.partCode,
            item.name,
            item.quantity,
            new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(item.unitPrice),
            new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(item.unitPrice * item.quantity),
        ];
        tableRows.push(itemData);
    });

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 55,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185] },
        styles: { fontSize: 9 },
    });

    // -- Totals --
    // @ts-ignore
    const finalY = doc.lastAutoTable.finalY + 10;

    doc.setFontSize(10);
    doc.text(`Subtotal:`, 140, finalY);
    doc.text(new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(quote.totalPrice), 170, finalY);

    // Simulating Tax Calculation for display if not stored explicitly on total yet
    // Assuming totalPrice in quote object is the final total.
    // Ideally we should break down tax vs subtotal if available. 
    // For now, based on schema, we have totalCost and totalPrice (which includes margin). 
    // Let's assume totalPrice is pre-tax or post-tax? 
    // In QuoteEditor, it seems tax is added. Let's just show the final Total Price as "Grand Total" for now 
    // to be safe, or recalculate if needed. Re-calculating visually.

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`Grand Total:`, 140, finalY + 8);
    doc.text(new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(quote.totalPrice), 170, finalY + 8);

    // -- Footer --
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text("Thank you for your business.", 14, finalY + 20);
    doc.text("Terms & Conditions: Prices valid for 30 days. Payment due on receipt.", 14, finalY + 25);

    doc.save(`Quote_${quote.clientName || "Export"}.pdf`);
};
